#!/bin/bash

# if there are any changes
if [[ $(git diff-index --exit-code HEAD _days today.md) ]]; then
  # commit and push
  git add -A _days today.md
  git commit -S -m "$(date)"
  git push --quiet &
fi
